### ISSUE TITLE
Mac2 Driver - Not Able to See Accessibility Id in pageSource When Dealing with SwiftUI Elements on Mac Desktop Application

### ISSUE THREAD

**Issue by jeff-eg** [appium/appium-mac2-driver#146]
Hello,

Currently when we add accessibility id’s in swift ui elements for our mac desktop application I am not seeing the id’s in the driver.PageSource. Is anyone else seeing this problem?

Here is a discussion of things in the appium forums...
https://discuss.appium.io/t/mac2-driver-not-able-to-see-accessibility-id-with-swiftui-elements-on-mac-desktop-application/36702 

I can however see the accessibility ids in the xcode accessibility inspector.  

This seems to be a bug with mac2 driver and swift ui elements

**Comment by mykola-mokhnach** [comment]
I don't think there is much we could do there. WDA uses the official XCTest API https://developer.apple.com/documentation/xctest/xcuielementsnapshotproviding/3022452-snapshot to fetch the tree. Perhaps, elements you are looking for are just attached to another accessibility root rather than the current app root. Then you could try to [switch](https://github.com/appium/appium-mac2-driver#application-under-test-concept) to another app as a possible solution. Otherwise I don't have any good ideas so far.

**Comment by jeff-eg** [comment]
Ok.  I'll continue to figure things out.  Thank you!
